// Assembles the DHCW.SingleRecord.Blazor NuGet project from the built web CSS.
//
// Why this exists, and why it replaced a hand copy: `packages/blazor/wwwroot/`
// used to be a manual mirror of three files, refreshed by copy commands written
// in the csproj *as a comment that nothing ran*. It drifted, and it shipped a
// fraction of the system — tokens plus button.css, while a web consumer got all
// 21 components. Generating it removes the failure mode rather than checking
// for it.
//
// What a Blazor consumer gets is deliberately the same style layer a web
// consumer gets, from the same built files:
//
//     single-record.css       every component, tokens and font, one link
//     single-record-dark.css  dark-mode overrides, opt-in, loaded second
//     foundations.css         tokens and type only, no components
//     sprite.svg              the icon set for <use> references
//     components/*.css        one component at a time
//
// Served to any host at _content/DHCW.SingleRecord.Blazor/css/… by the RCL
// static web asset mechanism.
//
// This package is the token and style layer, matching what packages/maui ships
// for MAUI. It is not a Razor component library: a Blazor consumer writes their
// own markup with the sr-* classes, exactly as an HTML consumer does. SrButton
// stays in packages/blazor/src for the preview gallery and is not packaged —
// shipping one component of twenty-one would imply a set that does not exist.
//
// Run via `npm run build:blazor` at the repository root.

import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(here, '../..');
const DIST = resolve(ROOT, 'packages/web/dist');
const OUT = resolve(here, 'nuget');
const CSS_OUT = resolve(OUT, 'wwwroot/css');
const PKG_ID = 'DHCW.SingleRecord.Blazor';

if (!existsSync(DIST)) {
  console.error(`::error::${DIST} is missing. Run "npm run build:web" first.`);
  process.exit(1);
}

// One source for the version, patched in rather than maintained in two places.
// The npm release workflow once hardcoded "0.1.0" in the URLs it advertised
// while the packages sat at 0.1.1, and nothing noticed.
const VERSION = JSON.parse(readFileSync(resolve(here, 'package.json'), 'utf8')).version;

// Rebuild from scratch: a file deleted upstream must not survive here.
rmSync(OUT, { recursive: true, force: true });
mkdirSync(CSS_OUT, { recursive: true });

const TOP_LEVEL = [
  'single-record.css',
  'single-record-dark.css',
  'foundations.css',
  'sprite.svg',
];

for (const f of TOP_LEVEL) {
  const src = resolve(DIST, f);
  if (!existsSync(src)) {
    console.error(`::error::${f} is not in packages/web/dist. Run "npm run build:web".`);
    process.exit(1);
  }
  cpSync(src, resolve(CSS_OUT, f));
}
cpSync(resolve(DIST, 'components'), resolve(CSS_OUT, 'components'), { recursive: true });

const componentCount = readFileSync(resolve(DIST, 'single-record.css'), 'utf8')
  .match(/^\/\* ─+ [a-z-]+ ─+ \*\/$/gm)?.length ?? null;

writeFileSync(resolve(OUT, `${PKG_ID}.csproj`), `<Project Sdk="Microsoft.NET.Sdk.Razor">

  <!--
    GENERATED by packages/blazor/build-nuget.mjs. Do not edit.

    Everything under wwwroot/ is copied from packages/web/dist, which is itself
    built from the tokens and component sources. Editing it here is silently
    overwritten on the next build and puts Blazor out of step with web.
  -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>${PKG_ID}</RootNamespace>
    <AssemblyName>${PKG_ID}</AssemblyName>

    <!-- Hosts reference the CSS at _content/${PKG_ID}/css/… -->
    <StaticWebAssetBasePath>_content/${PKG_ID}</StaticWebAssetBasePath>

    <IsPackable>true</IsPackable>
    <PackageId>${PKG_ID}</PackageId>
    <Version>${VERSION}</Version>
    <Authors>Digital Health and Care Wales</Authors>
    <Company>Digital Health and Care Wales</Company>
    <Product>Single Record Design System</Product>
    <Description>Blazor token and style layer for the DHCW Single Record Design System: colour, spacing, elevation and type tokens, the full component stylesheet, dark-mode overrides and the icon sprite. Generated from the same sources as the web CSS, so the two cannot drift. This is a style layer, not a Razor component library — write your own markup with the sr-* classes.</Description>
    <PackageTags>dhcw;nhs;nhs-wales;design-system;blazor;razor;css;tokens;accessibility</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://dhcw-digital-health-and-care-wales.github.io/single-record-design-system/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/DHCW-Digital-Health-and-Care-Wales/single-record-design-system</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <None Include="README.md" Pack="true" PackagePath="\\" />
  </ItemGroup>

</Project>
`);

writeFileSync(resolve(OUT, 'README.md'), `# ${PKG_ID}

The DHCW Single Record Design System's **token and style layer for Blazor**.

Generated from the same sources as the web CSS, so the two cannot drift.

## What this is, and is not

It ships stylesheets, not Razor components. You write your own markup using the
\`sr-*\` classes, exactly as an HTML consumer does. That is the same shape as
\`DHCW.SingleRecord.Maui\`, which ships resource dictionaries rather than
controls.

## Install

\`\`\`
dotnet add package ${PKG_ID}
\`\`\`

The feed is GitHub Packages, which requires authentication even for public
packages. You need a \`nuget.config\` and a token with \`read:packages\`:

\`\`\`xml
<configuration>
  <packageSources>
    <add key="dhcw" value="https://nuget.pkg.github.com/DHCW-Digital-Health-and-Care-Wales/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <dhcw>
      <add key="Username" value="YOUR_GITHUB_USERNAME" />
      <add key="ClearTextPassword" value="YOUR_TOKEN_WITH_read:packages" />
    </dhcw>
  </packageSourceCredentials>
</configuration>
\`\`\`

## Use

In \`App.razor\` or \`_Host.cshtml\`, in this order:

\`\`\`html
<link rel="stylesheet" href="_content/${PKG_ID}/css/single-record.css" />

<!-- Dark mode is opt-in and must load SECOND: it overrides the tokens above. -->
<link rel="stylesheet" href="_content/${PKG_ID}/css/single-record-dark.css" />
\`\`\`

Then set \`data-theme="dark"\` on \`<html>\` to switch.

Then write markup:

\`\`\`razor
<button class="sr-button sr-button--primary" @onclick="Confirm">Confirm patient</button>
\`\`\`

## What is in the package

| File | For |
|---|---|
| \`css/single-record.css\` | Everything: font, tokens, type utilities, all components |
| \`css/single-record-dark.css\` | Dark-mode token overrides. Opt-in, load second |
| \`css/foundations.css\` | Tokens and type only, no components |
| \`css/sprite.svg\` | The icon set, for \`<use>\` references |
| \`css/components/*.css\` | One component at a time, if you do not want the bundle |

## Version

${VERSION}, versioned in lockstep with the npm packages and
\`DHCW.SingleRecord.Maui\` — one version number describes the whole design system.
`);

const cssFiles = TOP_LEVEL.length;
console.log(`@dhcw/sr-blazor: NuGet project assembled — v${VERSION}, `
  + `${cssFiles} top-level stylesheets`
  + (componentCount ? `, ${componentCount} components in the bundle` : '')
  + `, plus per-component CSS.`);
