// Generates src/assets/logo.js (data-URI brand marks) from the committed brand
// rasters in figma/assets/. Run via `npm run build:logo`.
//
// Why a generated module rather than plain file references: logo.js has three
// consumers with incompatible loaders — Storybook (Vite), packages/website
// build.mjs (plain Node, embeds into an HTML string), and the React stories.
// A data URI is the one form all three consume without a build rule each.
//
// The source rasters are the official GIG Cymru / NHS Wales / DHCW lockups and
// are trademarked. This script only repackages them — it does not modify the
// artwork. Figma's Logos component (270:2850) states: "Do not stretch, rotate,
// recolour, or crop logos."

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const assetsDir = resolve(here, '../../figma/assets');
const outFile = resolve(here, 'src/assets/logo.js');

const dataUri = (file) => {
  const bytes = readFileSync(resolve(assetsDir, file));
  if (bytes.length === 0) throw new Error(`${file} is empty`);
  return `data:image/png;base64,${bytes.toString('base64')}`;
};

const full = dataUri('dhcw-logo-blue.png');

// The icon-only mark (Figma "Type=Icon, Subgroup=dhcw") has no committed source
// asset yet, so the symbol below remains a NEUTRAL PLACEHOLDER. It must not be
// derived by cropping the lockup — see the brand note above. Replace this
// branch once figma/assets/dhcw-logo-icon-*.png (or .svg) is committed.
const placeholderSymbol =
  '<rect width="40" height="40" rx="8" fill="#325083"/>' +
  '<polygon points="20,8 32,20 20,32 8,20" fill="none" stroke="#ffffff" stroke-width="2.5"/>' +
  '<polygon points="20,15 25,20 20,25 15,20" fill="#ffffff"/>';

const symbol =
  'data:image/svg+xml;utf8,' +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40">${placeholderSymbol}</svg>`
  );

const out = `// AUTO-GENERATED by packages/web/build-logo.mjs — do not edit directly.
// Source of truth: figma/assets/. Re-run \`npm run build:logo\` after changing
// a brand raster.
//
// Brand marks for the DHCW Single Record programme.
//
//   logoFullSrc   — official GIG Cymru / NHS Wales / DHCW lockup (navy, for
//                   light backgrounds). Real trademarked asset.
//   logoSymbolSrc — PLACEHOLDER. The official icon-only mark (Figma Logos
//                   270:2850, "Type=Icon, Subgroup=dhcw") has not been exported
//                   into this repo yet. Do NOT crop it out of the lockup.
//
// Do not stretch, rotate, recolour, or crop these marks. Scale uniformly only.

export const logoFullSrc =
  '${full}';

export const logoSymbolSrc =
  '${symbol}';
`;

writeFileSync(outFile, out);
console.log(
  `logo.js written — lockup ${(full.length / 1024).toFixed(1)}KB, symbol placeholder.`
);
