/**
 * Build the distributable web assets for the DHCW Single Record Design System.
 *
 * Why this exists: a developer adopting the system needs *files they can drop
 * into an application*. Reading a component's source on the design-system
 * website is not the same thing, and up to now that is all there was — this
 * package shipped 21 separate component stylesheets and a `main` field
 * pointing at an `index.css` that did not exist.
 *
 * Output (packages/web/dist/):
 *   single-record.css       everything: fonts, tokens, typography, icons, all
 *                           components. One <link>, no build tooling needed.
 *   single-record-dark.css  dark-mode token overrides, opt-in and loaded after.
 *   icons.js                the icon set as an ES module (iconMarkup, iconNames).
 *   sprite.svg              the same icons as an SVG sprite, for <use href>.
 *   components/*.css        the individual stylesheets, for anyone taking one
 *                           component at a time.
 *
 * No dependencies and no bundler — concatenation and file copies only, in the
 * same spirit as the token build. Adding a real bundler is a decision that
 * needs a DDR (CLAUDE.md), and nothing here needs one yet.
 *
 * Order matters exactly once: fonts and tokens must come before anything that
 * uses their custom properties. Components are emitted alphabetically after
 * that; they do not depend on each other's cascade position.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, basename } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');
const SRC = resolve(__dirname, 'src');
const DIST = resolve(__dirname, 'dist');
const TOKENS = resolve(ROOT, 'packages', 'tokens', 'build');
const ICONS = resolve(ROOT, 'packages', 'icons');
const ROOT_ASSETS = resolve(ROOT, 'figma', 'assets');

const pkg = JSON.parse(readFileSync(resolve(__dirname, 'package.json'), 'utf8'));

if (!existsSync(resolve(TOKENS, 'css', 'tokens.css'))) {
  console.error('Token build missing. Run `npm run build -w @dhcw/sr-tokens` first.');
  process.exit(1);
}

// Component stylesheets: every `src/<name>/<name>.css`. Discovered rather than
// listed, so a new component cannot be added to the repo and left out of the
// distributed bundle — the failure mode that produces "it works on the website
// but not in my app".
const componentFiles = readdirSync(SRC, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => resolve(SRC, d.name, `${d.name}.css`))
  .filter((f) => existsSync(f))
  .sort();

const banner = (title) => `/*!
 * DHCW Single Record Design System — ${title}
 * v${pkg.version} · generated by packages/web/build.mjs · do not edit by hand.
 * Licence: MIT. Roboto is embedded under the Apache 2.0 licence.
 */
`;

const section = (label, css) => `\n/* ═══ ${label} ${'═'.repeat(Math.max(0, 60 - label.length))} */\n${css.trim()}\n`;

rmSync(DIST, { recursive: true, force: true });
mkdirSync(resolve(DIST, 'components'), { recursive: true });

// ── foundations.css ──────────────────────────────────────────────────────────
// Everything that is NOT a component: the font, the tokens, and the typography
// utilities. This is the file a bundler-based consumer wants.
//
// Why it exists: every React component imports its own stylesheet
// (`import '@dhcw/sr-web/src/button/button.css'`), so an app that also loads
// single-record.css gets all 21 component stylesheets AND a second copy of each
// one it actually uses. Pairing this with the React package means an app ships
// the foundations plus only the components it imports.
//
// Plain HTML has no bundler to assemble the pieces and should keep using
// single-record.css.
const foundationParts = [
  ['fonts', readFileSync(resolve(TOKENS, 'css', 'fonts.css'), 'utf8')],
  ['tokens (light)', readFileSync(resolve(TOKENS, 'css', 'tokens.css'), 'utf8')],
  ['typography utilities', readFileSync(resolve(TOKENS, 'css', 'typography.css'), 'utf8')],
];
writeFileSync(
  resolve(DIST, 'foundations.css'),
  banner('foundations only: font, tokens and typography — no components')
    + foundationParts.map(([l, c]) => section(l, c)).join('')
);

// ── single-record.css ────────────────────────────────────────────────────────
const parts = [
  ...foundationParts,
  ['icons', readFileSync(resolve(ICONS, 'src', 'icon.css'), 'utf8')],
  ...componentFiles.map((f) => [basename(f, '.css'), readFileSync(f, 'utf8')]),
];
writeFileSync(
  resolve(DIST, 'single-record.css'),
  banner('complete stylesheet') + parts.map(([l, c]) => section(l, c)).join('')
);

// ── dark mode, separate and opt-in ───────────────────────────────────────────
// Kept out of the main file deliberately: it is token overrides only, a product
// loads it when it supports dark mode, and it must win the cascade, so it has
// to come second. See DESIGN-SYSTEM.md — the dark values are provisional until
// the light-mode semantic assignments settle.
writeFileSync(
  resolve(DIST, 'single-record-dark.css'),
  banner('dark-mode token overrides (load AFTER single-record.css)')
    + section('tokens (dark)', readFileSync(resolve(TOKENS, 'css', 'tokens-dark.css'), 'utf8'))
);

// ── per-component stylesheets ────────────────────────────────────────────────
for (const f of componentFiles) copyFileSync(f, resolve(DIST, 'components', basename(f)));
copyFileSync(resolve(ICONS, 'src', 'icon.css'), resolve(DIST, 'components', 'icon.css'));

// ── Brand marks ──────────────────────────────────────────────────────────────
// Shipped as real files as well as the data URIs in src/assets/logo.js: a MAUI
// app, a Blazor wwwroot or a designer wants a path to reference, not a URI
// embedded in a JS module.
//
// These live apart from the icon set on purpose, and the two contracts are
// opposites. An icon inherits currentColor and is meant to be recoloured; a
// brand mark must never be. That is why there is a blue file and a white file
// rather than one file and a CSS rule — you pick the variant that suits the
// background. Putting these in @dhcw/sr-icons would licence exactly the
// behaviour the brand rules forbid.
const BRAND_FILES = [
  'dhcw-logo-blue.png',
  'dhcw-symbol-blue.svg', 'dhcw-symbol-white.svg',
  'wcp-symbol-blue.svg', 'wcp-symbol-white.svg',
  'wcp-logo-blue.svg', 'wcp-logo-white.svg',
  'nhs-wales-symbol-blue.svg', 'nhs-wales-symbol-white.svg',
  'nhs-wales-logo-colour.svg', 'nhs-wales-logo-white.svg',
  'wncr-symbol-white.svg',
];
mkdirSync(resolve(DIST, 'logos'), { recursive: true });
for (const f of BRAND_FILES) {
  copyFileSync(resolve(ROOT_ASSETS, f), resolve(DIST, 'logos', f));
}

// ── JavaScript: the icon set ─────────────────────────────────────────────────
// The only JavaScript the HTML/CSS layer needs. Components here are plain
// markup — behaviour lives in the React and Blazor wrappers — but icons are
// generated, so a consumer needs either this module or the sprite.
copyFileSync(resolve(ICONS, 'build', 'icons.js'), resolve(DIST, 'icons.js'));
copyFileSync(resolve(ICONS, 'build', 'sprite.svg'), resolve(DIST, 'sprite.svg'));

const kb = (p) => `${Math.round(readFileSync(resolve(DIST, p)).length / 1024)}KB`;
console.log(`Web assets built to ${DIST}`);
console.log(`  foundations.css        ${kb('foundations.css')}  (font + tokens + typography, no components)`);
console.log(`  single-record.css      ${kb('single-record.css')}  (${componentFiles.length} components + tokens + fonts)`);
console.log(`  single-record-dark.css ${kb('single-record-dark.css')}`);
console.log(`  icons.js               ${kb('icons.js')}`);
console.log(`  sprite.svg             ${kb('sprite.svg')}`);
