// Generates src/assets/logo.js (data-URI brand marks) from the committed brand
// rasters in figma/assets/. Run via `npm run build:logo`.
//
// Why a generated module rather than plain file references: logo.js has three
// consumers with incompatible loaders — Storybook (Vite), packages/website
// build.mjs (plain Node, embeds into an HTML string), and the React stories.
// A data URI is the one form all three consume without a build rule each.
//
// The source rasters are the official GIG Cymru / NHS Wales / DHCW lockups and
// are trademarked. This script only repackages them — it does not modify the
// artwork. Figma's Logos component (270:2850) states: "Do not stretch, rotate,
// recolour, or crop logos."

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const assetsDir = resolve(here, '../../figma/assets');
const outFile = resolve(here, 'src/assets/logo.js');

const dataUri = (file) => {
  const bytes = readFileSync(resolve(assetsDir, file));
  if (bytes.length === 0) throw new Error(`${file} is empty`);
  return `data:image/png;base64,${bytes.toString('base64')}`;
};

// SVG is inlined as utf8 rather than base64: it stays legible in a diff and is
// smaller than the base64 of the same bytes.
const svgDataUri = (file) => {
  const svg = readFileSync(resolve(assetsDir, file), 'utf8').trim();
  if (svg.length === 0) throw new Error(`${file} is empty`);
  if (svg.includes("'")) throw new Error(`${file} contains a single quote`);
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
};

const full = dataUri('dhcw-logo-blue.png');

// The icon-only mark, traced from the Figma Logos component's own vector
// (270:2850, "Type=Icon, Subgroup=dhcw") — it is the authored mark, not a crop
// of the lockup. Light-background (navy) variant; the white variant for dark
// backgrounds is committed alongside it as dhcw-symbol-white.svg.
const symbol = svgDataUri('dhcw-symbol-blue.svg');
const symbolInverse = svgDataUri('dhcw-symbol-white.svg');

// Welsh Clinical Portal, lifted from the Figma Logos component's own
// fillGeometry (wcp/Icon). Unlike the DHCW open knot, the WCP mark is a filled
// roundel — verified against a render of the Figma node, not assumed.
//
// Named by ink colour, not by Figma's "Colour mode" variant. That variant name
// is not consistent between subgroups in the Figma file: nhs_wales/Icon/light
// is navy, but wcp/Icon/light is white. Naming a file after it would ship an
// invisible logo. Blue = for light backgrounds; white = for dark ones.
const wcpSymbol = svgDataUri('wcp-symbol-blue.svg');
const wcpSymbolInverse = svgDataUri('wcp-symbol-white.svg');

const out = `// AUTO-GENERATED by packages/web/build-logo.mjs — do not edit directly.
// Source of truth: figma/assets/. Re-run \`npm run build:logo\` after changing
// a brand raster.
//
// Brand marks for the DHCW Single Record programme.
//
//   logoFullSrc   — official GIG Cymru / NHS Wales / DHCW lockup (navy, for
//                   light backgrounds). Real trademarked asset.
//   logoSymbolSrc — official icon-only mark (navy, for light backgrounds),
//                   from the Figma Logos component 270:2850,
//                   "Type=Icon, Subgroup=dhcw, Colour mode=light".
//   logoSymbolInverseSrc
//                 — the same mark in white, for dark backgrounds
//                   ("Colour mode=dark"). Use this instead of recolouring.
//   wcpSymbolSrc / wcpSymbolInverseSrc
//                 — Welsh Clinical Portal roundel, navy and white.
//
// These are brand marks, not icons. They do not inherit currentColor and must
// not be recoloured: pick the variant that suits the background instead.
//
// Do not stretch, rotate, recolour, or crop these marks. Scale uniformly only.

export const logoFullSrc =
  '${full}';

export const logoSymbolSrc =
  '${symbol}';

export const logoSymbolInverseSrc =
  '${symbolInverse}';

export const wcpSymbolSrc =
  '${wcpSymbol}';

export const wcpSymbolInverseSrc =
  '${wcpSymbolInverse}';
`;

writeFileSync(outFile, out);

console.log(
  `logo.js written — lockup ${(full.length / 1024).toFixed(1)}KB, ` +
    `symbol ${(symbol.length / 1024).toFixed(1)}KB, ` +
    `inverse ${(symbolInverse.length / 1024).toFixed(1)}KB, ` +
    `wcp ${(wcpSymbol.length / 1024).toFixed(1)}KB.`
);
