import './icon.css';
import { icons, iconNames } from '../build/icons.js';
import { icon } from './icon.js';

/**
 * Icon — DHCW Single Record Design System
 * Source: foundations/iconography/svg/ (Lucide-derived, ISC licence, see DDR-003).
 * Generated by packages/icons/build.js — 106 icons across 10 domains.
 */

const domains = [...new Set(iconNames.map((n) => n.split('/')[0]))].sort();

const renderGrid = (filterDomain) => {
  const wrap = document.createElement('div');
  wrap.style.cssText = 'font-family: Roboto, system-ui, sans-serif;';

  const names = filterDomain ? iconNames.filter((n) => n.startsWith(`${filterDomain}/`)) : iconNames;

  const grid = document.createElement('div');
  grid.style.cssText =
    'display:grid;grid-template-columns:repeat(auto-fill, minmax(140px, 1fr));gap:16px;';

  names.forEach((name) => {
    const cell = document.createElement('div');
    cell.style.cssText =
      'display:flex;flex-direction:column;align-items:center;gap:8px;padding:16px;border:1px solid var(--sr-color-border-default, #d8dde0);border-radius:4px;';
    const wrapper = icon(name, { size: 'lg', color: 'default' });
    cell.appendChild(wrapper);
    const label = document.createElement('span');
    label.textContent = name;
    label.style.cssText = 'font-size:12px;color:var(--sr-color-text-secondary,#4c6272);text-align:center;word-break:break-word;';
    cell.appendChild(label);
    grid.appendChild(cell);
  });

  wrap.appendChild(grid);
  return wrap;
};

export default {
  title: 'Foundations/Icons',
  tags: ['autodocs'],
  argTypes: {
    domain: {
      control: { type: 'select' },
      options: ['(all)', ...domains],
      description: 'Filter by icon domain/group.',
    },
  },
  args: {
    domain: '(all)',
  },
  render: ({ domain }) => renderGrid(domain === '(all)' ? undefined : domain),
};

/** Full library — every icon, every domain. */
export const AllIcons = {};

/** One story per domain, so each group can be reviewed/linked independently. */
export const Nav = { args: { domain: 'nav' } };
export const People = { args: { domain: 'people' } };
export const Clinical = { args: { domain: 'clinical' } };
export const Schedule = { args: { domain: 'schedule' } };
export const Action = { args: { domain: 'action' } };
export const Status = { args: { domain: 'status' } };

/** Size scale for a single representative icon — sr.icon.size.{xs,sm,md,lg}. */
export const Sizes = {
  argTypes: {},
  args: {},
  render: () => {
    const wrap = document.createElement('div');
    wrap.style.cssText = 'display:flex;align-items:flex-end;gap:24px;font-family: Roboto, system-ui, sans-serif;';
    ['xs', 'sm', 'md', 'lg'].forEach((size) => {
      const cell = document.createElement('div');
      cell.style.cssText = 'display:flex;flex-direction:column;align-items:center;gap:8px;';
      cell.appendChild(icon('nav/home', { size }));
      const label = document.createElement('span');
      label.textContent = size;
      label.style.cssText = 'font-size:12px;color:var(--sr-color-text-secondary,#4c6272);';
      cell.appendChild(label);
      wrap.appendChild(cell);
    });
    return wrap;
  },
};

/** Colour roles — sr.icon.color.*. */
export const Colors = {
  argTypes: {},
  args: {},
  render: () => {
    const wrap = document.createElement('div');
    wrap.style.cssText = 'display:flex;flex-wrap:wrap;gap:24px;font-family: Roboto, system-ui, sans-serif;';
    ['default', 'subtle', 'interactive', 'critical', 'warning', 'success', 'info'].forEach((color) => {
      const cell = document.createElement('div');
      cell.style.cssText = 'display:flex;flex-direction:column;align-items:center;gap:8px;';
      cell.appendChild(icon('status/flagged', { size: 'lg', color }));
      const label = document.createElement('span');
      label.textContent = color;
      label.style.cssText = 'font-size:12px;color:var(--sr-color-text-secondary,#4c6272);';
      cell.appendChild(label);
      wrap.appendChild(cell);
    });
    return wrap;
  },
};

// Avoid an unused-import lint failure — `icons` is part of the package's
// public surface and useful for consumers inspecting raw markup in the console.
void icons;
