// Generates Colors.xaml from the @dhcw/sr-tokens XAML output, then validates
// that every {StaticResource ...} in Styles.xaml resolves against it.
//
// Why this file exists rather than consuming Tokens.xaml directly:
//
//   @dhcw/sr-tokens emits Tokens.xaml and Tokens.Dark.xaml with the SAME key
//   names and different values. That shape suits a runtime dictionary swap, but
//   the Single Record mobile app themes with AppThemeBinding — which needs both
//   values reachable at once, under different keys. Merging both files would be
//   a key collision.
//
//   So Colors.xaml carries every key once, plus a `...Dark` twin for the 16
//   semantic tokens whose value actually differs between modes. Primitives are
//   identical in both modes and are not duplicated.
//
// DDR-021: MAUI is native XAML, and this package is its token and style layer.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const TOKENS = resolve(here, '../tokens/build/xaml');

const LIGHT = resolve(TOKENS, 'Tokens.xaml');
const DARK = resolve(TOKENS, 'Tokens.Dark.xaml');
for (const f of [LIGHT, DARK]) {
  if (!existsSync(f)) {
    throw new Error(`${f} is missing. Run \`npm run build -w @dhcw/sr-tokens\` first.`);
  }
}

/** Parse `<Tag x:Key="Name">value</Tag>` and multi-line elements alike. */
function parseDictionary(path) {
  const src = readFileSync(path, 'utf8');
  const out = new Map();
  // Single-line elements: the overwhelming majority (Color, x:Double, x:String).
  for (const m of src.matchAll(/^\s*<([\w:.]+)\s+x:Key="([^"]+)"\s*>([^<]*)<\/[\w:.]+>\s*$/gm)) {
    out.set(m[2], { tag: m[1], value: m[3], block: m[0].trim() });
  }
  // Anything else carrying an x:Key (shadows are emitted as nested elements).
  for (const m of src.matchAll(/^\s*<([\w:.]+)\s+x:Key="([^"]+)"(?![^>]*\/>)[^>]*>$/gm)) {
    if (!out.has(m[2])) out.set(m[2], { tag: m[1], value: null, block: null });
  }
  return out;
}

const light = parseDictionary(LIGHT);
const dark = parseDictionary(DARK);

const differing = [...light.keys()].filter(
  (k) => dark.has(k) && light.get(k).value !== null && light.get(k).value !== dark.get(k).value
);

const lines = [];
lines.push('<?xml version="1.0" encoding="utf-8"?>');
lines.push('<!--');
lines.push('    AUTO-GENERATED by packages/maui/build.mjs — do not edit by hand.');
lines.push('    Source of truth: foundations/tokens/**, via @dhcw/sr-tokens.');
lines.push('');
lines.push('    Every design value the Single Record mobile app should use, as XAML');
lines.push('    resources. Semantic tokens that change between light and dark carry a');
lines.push('    `Dark` twin, so a style can bind both at once:');
lines.push('');
lines.push('        {AppThemeBinding Light={StaticResource SrColorTextPrimary},');
lines.push('                         Dark={StaticResource SrColorTextPrimaryDark}}');
lines.push('');
lines.push('    Reach for the semantic names (SrColor…). The primitives below them');
lines.push('    (ColorBlue800 and friends) exist so the semantics have something to');
lines.push('    resolve to; binding a component straight to a primitive skips the layer');
lines.push('    that carries the meaning, and it will not follow a token change.');
lines.push('-->');
lines.push('<ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"');
lines.push('                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">');
lines.push('');
lines.push('    <!-- ── Light mode, and every value that does not change with the theme ── -->');
for (const [key, entry] of light) {
  if (entry.block) lines.push(`    ${entry.block}`);
}
lines.push('');
lines.push(`    <!-- ── Dark-mode overrides (${differing.length} semantic tokens) ────────────────────── -->`);
for (const key of differing) {
  const d = dark.get(key);
  lines.push(`    <${d.tag} x:Key="${key}Dark">${d.value}</${d.tag}>`);
}
lines.push('');
lines.push('</ResourceDictionary>');

const outPath = resolve(here, 'Colors.xaml');
writeFileSync(outPath, lines.join('\n') + '\n');

// ─── Validate Styles.xaml against what we just emitted ───────────────────────
const known = new Set([...light.keys(), ...differing.map((k) => `${k}Dark`)]);
const stylesPath = resolve(here, 'Styles.xaml');
let problems = [];

if (existsSync(stylesPath)) {
  const styles = readFileSync(stylesPath, 'utf8');

  // Every resource this file defines itself is also legitimately referenceable.
  for (const m of styles.matchAll(/x:Key="([^"]+)"/g)) known.add(m[1]);

  const seen = new Set();
  for (const m of styles.matchAll(/\{StaticResource\s+([^}]+?)\s*\}/g)) {
    const name = m[1].trim();
    if (seen.has(name)) continue;
    seen.add(name);
    if (!known.has(name)) problems.push(name);
  }

  // A style that hard-codes a colour has skipped the token layer entirely.
  //
  // In XAML the value almost always arrives as `<Setter Value="..." />` rather
  // than on a named colour attribute, so both forms are checked. Transparent is
  // not a colour choice — it is the absence of one — and stays allowed.
  const NAMED = 'Red|Blue|Green|Maroon|Navy|Teal|Olive|Purple|Silver|Black|White'
    + '|Gray|Grey|DarkGray|DarkGrey|LightGray|LightGrey|Orange|Yellow|Pink|Brown|Cyan|Magenta';
  const literalValue = new RegExp(`(?:Value|Color|BackgroundColor|TextColor|Stroke|Fill|BorderColor|PlaceholderColor|ThumbColor|OnColor|TitleColor)\\s*=\\s*"(#[0-9A-Fa-f]{3,8}|${NAMED})"`, 'g');
  for (const m of styles.matchAll(literalValue)) {
    problems.push(`literal colour "${m[1]}" — every colour must come from a token`);
  }
}

if (problems.length) {
  console.error(`\n@dhcw/sr-maui: ${problems.length} problem(s) in Styles.xaml:\n`);
  for (const p of problems) console.error(`  ${p}`);
  console.error('\nEvery colour must come from Colors.xaml. Add the token, or fix the reference.\n');
  process.exit(1);
}

console.log(
  `@dhcw/sr-maui: Colors.xaml written — ${light.size} resources, `
  + `${differing.length} with dark-mode twins.`
  + (existsSync(stylesPath) ? ' Styles.xaml references all resolve.' : ' (Styles.xaml not present yet.)')
);
