/**
 * Token build pipeline — Style Dictionary 4.x
 *
 * Reads: /foundations/tokens/ (W3C DTCG format)
 * Outputs:
 *   build/css/tokens.css           — CSS custom properties (light mode)
 *   build/css/tokens-dark.css      — CSS custom properties (dark mode)
 *   build/scss/_tokens.scss        — SCSS variables (light mode)
 *   build/scss/_tokens-dark.scss   — SCSS variables (dark mode)
 *   build/xaml/Tokens.xaml         — XAML ResourceDictionary (light mode, for MAUI)
 *   build/xaml/Tokens.Dark.xaml    — XAML ResourceDictionary (dark mode, for MAUI)
 *   build/json/tokens-flat.json    — Flat key-value JSON (for tooling/CI)
 */

import StyleDictionary from 'style-dictionary';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TOKENS_ROOT = path.resolve(__dirname, '../../foundations/tokens');

// ---------------------------------------------------------------------------
// Custom format: XAML ResourceDictionary for .NET MAUI
// ---------------------------------------------------------------------------
const xamlFormat = {
  name: 'xaml/resourceDictionary',
  format: ({ dictionary }) => {
    const header = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by @dhcw/sr-tokens — do not edit manually -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
`;
    const footer = `</ResourceDictionary>\n`;

    const entries = dictionary.allTokens.map(token => {
      const name = token.name;
      const val = token.$value ?? token.value;
      const type = token.$type || token.type || '';

      if (type === 'color') {
        return `    <Color x:Key="${name}">${val}</Color>`;
      }
      if (type === 'dimension') {
        const numVal = parseFloat(val);
        return `    <x:Double x:Key="${name}">${numVal}</x:Double>`;
      }
      return `    <x:String x:Key="${name}">${val}</x:String>`;
    });

    return header + entries.join('\n') + '\n' + footer;
  }
};

// Flat JSON for tooling
const flatJsonFormat = {
  name: 'json/flat-map',
  format: ({ dictionary }) => {
    const result = {};
    dictionary.allTokens.forEach(token => {
      result[token.name] = token.$value ?? token.value;
    });
    return JSON.stringify(result, null, 2) + '\n';
  }
};

// ---------------------------------------------------------------------------
// Custom format: responsive typography utility classes
//
// CSS has no single property for the DTCG `typography` composite, so dumping
// these as custom properties produces `[object Object]`. Instead we emit
// mobile-first utility classes (`.sr-type-{name}`) whose base values are the
// mobile scale, overridden at the desktop breakpoint. See DDR-005 (scale) and
// DDR-011 (desktop/mobile form-factor model).
// ---------------------------------------------------------------------------
const typographyClassesFormat = {
  name: 'css/typography-utilities',
  format: ({ dictionary }) => {
    const bp = dictionary.allTokens.find(t => t.name.endsWith('breakpoint-desktop-min'));
    const desktopMin = (bp && (bp.$value ?? bp.value)) || '1024px';

    // Group the per-form-factor composites back together by semantic name.
    const groups = {};
    for (const t of dictionary.allTokens) {
      if ((t.$type || t.type) !== 'typography') continue;
      const formFactor = t.path[t.path.length - 1];                 // 'desktop' | 'mobile'
      const name = t.path.slice(t.path.indexOf('typography') + 1, -1).join('-');
      (groups[name] = groups[name] || {})[formFactor] = t.$value ?? t.value;
    }

    const decls = (v, indent) => {
      const fam = Array.isArray(v.fontFamily) ? v.fontFamily.join(', ') : v.fontFamily;
      return [
        `font-family: ${fam}, Arial, sans-serif;`,
        `font-size: ${v.fontSize};`,
        `line-height: ${v.lineHeight};`,
        `font-weight: ${v.fontWeight};`,
        `letter-spacing: ${v.letterSpacing};`,
      ].map(l => indent + l).join('\n');
    };

    const base = [];
    const overrides = [];
    for (const [name, vals] of Object.entries(groups)) {
      const mobile = vals.mobile || vals.desktop;
      const desktop = vals.desktop || vals.mobile;
      base.push(`.sr-type-${name} {\n${decls(mobile, '  ')}\n}`);
      if (JSON.stringify(mobile) !== JSON.stringify(desktop)) {
        overrides.push(`  .sr-type-${name} {\n${decls(desktop, '    ')}\n  }`);
      }
    }

    let out = `/**\n` +
      ` * Auto-generated by @dhcw/sr-tokens — do not edit manually.\n` +
      ` * Responsive typography utility classes (mobile-first): the base rule is the\n` +
      ` * mobile scale; the desktop scale is applied at min-width: ${desktopMin}.\n` +
      ` * Apply directly, e.g. <h1 class="sr-type-heading-xl">…</h1>\n` +
      ` */\n\n`;
    out += base.join('\n\n') + '\n';
    if (overrides.length) {
      out += `\n@media (min-width: ${desktopMin}) {\n${overrides.join('\n\n')}\n}\n`;
    }
    return out;
  }
};

// Composite typography tokens cannot be expressed as single CSS/SCSS variables —
// exclude them from the variable dumps (they are emitted as utility classes instead).
const excludeTypography = (token) => (token.$type || token.type) !== 'typography';

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------
const kebabTransform = {
  name: 'name/kebab-sr',
  type: 'name',
  transform: (token) => {
    return token.path
      .join('-')
      .toLowerCase()
      .replace(/\s+/g, '-');
  }
};

const pascalTransform = {
  name: 'name/pascal-sr',
  type: 'name',
  transform: (token) => {
    return token.path
      .map(p => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
      .replace(/[-\s]+(\w)/g, (_, c) => c.toUpperCase());
  }
};

// ---------------------------------------------------------------------------
// Shared source files (non-colour)
// ---------------------------------------------------------------------------
const sharedSources = [
  `${TOKENS_ROOT}/primitives/spacing.json`,
  `${TOKENS_ROOT}/primitives/typography.json`,
  `${TOKENS_ROOT}/primitives/iconography.json`,
  `${TOKENS_ROOT}/semantic/typography.json`,
  `${TOKENS_ROOT}/semantic/spacing.json`,
  `${TOKENS_ROOT}/breakpoints.json`,
  `${TOKENS_ROOT}/border.json`,
  `${TOKENS_ROOT}/elevation.json`,
  `${TOKENS_ROOT}/touch-targets.json`,
  `${TOKENS_ROOT}/logo-sizing.json`,
];

// Filter out files that don't exist
import { existsSync } from 'fs';
const existingSources = (sources) => sources.filter(s => {
  if (s.includes('*')) return true;
  return existsSync(s);
});

// ---------------------------------------------------------------------------
// Build configs
// ---------------------------------------------------------------------------
function makeConfig(mode) {
  const isDark = mode === 'dark';
  const colorSource = isDark
    ? `${TOKENS_ROOT}/semantic/color.dark.json`
    : `${TOKENS_ROOT}/semantic/color.json`;

  return {
    usesDtcg: true,
    log: { verbosity: 'silent' },
    hooks: {
      preprocessors: {
        'strip-dtcg-meta': (dictionary) => {
          delete dictionary.$schema;
          delete dictionary.$description;
          return dictionary;
        }
      },
      formats: {
        'xaml/resourceDictionary': xamlFormat.format,
        'json/flat-map': flatJsonFormat.format,
        'css/typography-utilities': typographyClassesFormat.format,
      },
      transforms: {
        'name/kebab-sr': kebabTransform,
        'name/pascal-sr': pascalTransform,
      }
    },
    preprocessors: ['strip-dtcg-meta'],
    source: existingSources([
      `${TOKENS_ROOT}/primitives/color.json`,
      colorSource,
      ...sharedSources,
    ]),
    platforms: {
      css: {
        transforms: ['name/kebab-sr', 'color/css'],
        buildPath: 'build/css/',
        prefix: 'sr',
        files: [
          {
            destination: isDark ? 'tokens-dark.css' : 'tokens.css',
            format: 'css/variables',
            filter: excludeTypography,
            options: {
              outputReferences: false,
              selector: isDark ? '[data-theme="dark"]' : ':root'
            }
          },
          // Responsive typography utility classes — light/theme-agnostic, emit once.
          ...(isDark ? [] : [{
            destination: 'typography.css',
            format: 'css/typography-utilities',
          }])
        ]
      },
      scss: {
        transforms: ['name/kebab-sr', 'color/css'],
        buildPath: 'build/scss/',
        prefix: 'sr',
        files: [{
          destination: isDark ? '_tokens-dark.scss' : '_tokens.scss',
          format: 'scss/variables',
          filter: excludeTypography,
          options: { outputReferences: false }
        }]
      },
      ...(isDark ? {} : {
        json: {
          transforms: ['name/kebab-sr', 'color/css'],
          buildPath: 'build/json/',
          files: [{
            destination: 'tokens-flat.json',
            format: 'json/flat-map'
          }]
        }
      }),
      xaml: {
        transforms: ['name/pascal-sr', 'color/css'],
        buildPath: 'build/xaml/',
        files: [{
          destination: isDark ? 'Tokens.Dark.xaml' : 'Tokens.xaml',
          format: 'xaml/resourceDictionary',
          filter: excludeTypography
        }]
      }
    }
  };
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
async function build() {
  console.log('\nBuilding light-mode tokens...');
  const sdLight = new StyleDictionary(makeConfig('light'));
  await sdLight.buildAllPlatforms();

  console.log('\nBuilding dark-mode tokens...');
  const sdDark = new StyleDictionary(makeConfig('dark'));
  await sdDark.buildAllPlatforms();

  console.log('\nToken build complete. Outputs in packages/tokens/build/');
}

build().catch(err => {
  console.error('Token build failed:', err);
  process.exit(1);
});
