/**
 * Token build pipeline — Style Dictionary 4.x
 *
 * Reads: /foundations/tokens/ (W3C DTCG format)
 * Outputs:
 *   build/css/tokens.css           — CSS custom properties (light mode)
 *   build/css/tokens-dark.css      — CSS custom properties (dark mode)
 *   build/scss/_tokens.scss        — SCSS variables (light mode)
 *   build/scss/_tokens-dark.scss   — SCSS variables (dark mode)
 *   build/xaml/Tokens.xaml         — XAML ResourceDictionary (light mode, for MAUI)
 *   build/xaml/Tokens.Dark.xaml    — XAML ResourceDictionary (dark mode, for MAUI)
 *   build/json/tokens-flat.json    — Flat key-value JSON (for tooling/CI)
 *   build/css/fonts.css            — @font-face for Roboto, font embedded as a
 *                                    data URI (see emitFontFace below)
 */

import StyleDictionary from 'style-dictionary';
import path from 'path';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TOKENS_ROOT = path.resolve(__dirname, '../../foundations/tokens');

// ---------------------------------------------------------------------------
// Custom format: XAML ResourceDictionary for .NET MAUI
// ---------------------------------------------------------------------------

/**
 * Parse a CSS `box-shadow` value into the parts MAUI's Shadow type needs.
 * Handles the two forms this system uses: `0 1px 4px rgba(r,g,b,a)` and
 * `0 2px 0 #RRGGBB`. Returns null for anything else rather than guessing —
 * an unparsed shadow surfaces as an XML comment in the output, which is
 * visible in review, instead of silently emitting something wrong.
 */
function parseCssShadow(value) {
  const v = String(value).trim();
  const rgba = v.match(
    /^(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/
  );
  if (rgba) {
    const [, x, y, radius, r, g, b, a] = rgba;
    const hex =
      '#' +
      [r, g, b]
        .map((n) => Number(n).toString(16).padStart(2, '0').toUpperCase())
        .join('');
    return { x, y, radius, hex, opacity: a === undefined ? '1' : a };
  }
  const hexForm = v.match(/^(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(#[0-9a-fA-F]{6})$/);
  if (hexForm) {
    const [, x, y, radius, hex] = hexForm;
    return { x, y, radius, hex: hex.toUpperCase(), opacity: '1' };
  }
  return null;
}

const xamlFormat = {
  name: 'xaml/resourceDictionary',
  format: ({ dictionary }) => {
    const header = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by @dhcw/sr-tokens — do not edit manually -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
`;
    const footer = `</ResourceDictionary>\n`;

    const entries = dictionary.allTokens.map(token => {
      const name = token.name;
      const val = token.$value ?? token.value;
      const type = token.$type || token.type || '';

      if (type === 'color') {
        return `    <Color x:Key="${name}">${val}</Color>`;
      }
      if (type === 'dimension') {
        const numVal = parseFloat(val);
        return `    <x:Double x:Key="${name}">${numVal}</x:Double>`;
      }
      if (type === 'shadow') {
        const s = parseCssShadow(val);
        if (!s) return `    <!-- ${name}: could not parse "${val}" as a shadow -->`;
        // MAUI has a first-class Shadow type. Emitting the CSS string here would
        // give .NET something it cannot consume, so build the real object.
        return [
          `    <Shadow x:Key="${name}"`,
          `            Brush="${s.hex}"`,
          `            Offset="${s.x},${s.y}"`,
          `            Radius="${s.radius}"`,
          `            Opacity="${s.opacity}" />`,
        ].join('\n');
      }
      return `    <x:String x:Key="${name}">${val}</x:String>`;
    });

    return header + entries.join('\n') + '\n' + footer;
  }
};

// Flat JSON for tooling
const flatJsonFormat = {
  name: 'json/flat-map',
  format: ({ dictionary }) => {
    const result = {};
    dictionary.allTokens.forEach(token => {
      result[token.name] = token.$value ?? token.value;
    });
    return JSON.stringify(result, null, 2) + '\n';
  }
};

// ---------------------------------------------------------------------------
// Custom format: responsive typography utility classes + composite properties
//
// Two surfaces are emitted from the same source, so they can never disagree:
//
//   1. `.sr-type-{name}` utility classes, for markup that can add a class.
//   2. `--sr-type-{name}-font` / `--sr-type-{name}-letter-spacing` custom
//      properties, for component CSS that cannot.
//
// (2) exists because component stylesheets can't apply a utility class they
// don't own, so they were each hand-picking raw --font-size-*/--font-line-
// height-*/--font-letter-spacing-* tokens — and routinely picked three of the
// four, or paired a size with the wrong line height. That is how 16px/700 and
// 12px/20px crept in, neither of which is on the scale.
//
// The CSS `font` shorthand carries weight, size, line-height and family in one
// value, so a component applies a complete named style in exactly two
// declarations that cannot be partially applied:
//
//   .sr-nav__item {
//     font: var(--sr-type-body-s-font);
//     letter-spacing: var(--sr-type-body-s-letter-spacing);
//   }
//
// Note `font` resets font-style/variant/stretch to normal, which is what we
// want. Both surfaces are mobile-first, overridden at the desktop breakpoint.
// See DDR-005 (scale) and DDR-011 (desktop/mobile form-factor model).
// ---------------------------------------------------------------------------
const typographyClassesFormat = {
  name: 'css/typography-utilities',
  format: ({ dictionary }) => {
    const bp = dictionary.allTokens.find(t => t.name.endsWith('breakpoint-desktop-min'));
    const desktopMin = (bp && (bp.$value ?? bp.value)) || '1024px';

    // Group the per-form-factor composites back together by semantic name.
    const groups = {};
    for (const t of dictionary.allTokens) {
      if ((t.$type || t.type) !== 'typography') continue;
      const formFactor = t.path[t.path.length - 1];                 // 'desktop' | 'mobile'
      const name = t.path.slice(t.path.indexOf('typography') + 1, -1).join('-');
      (groups[name] = groups[name] || {})[formFactor] = t.$value ?? t.value;
    }

    const decls = (v, indent) => {
      const fam = Array.isArray(v.fontFamily) ? v.fontFamily.join(', ') : v.fontFamily;
      return [
        `font-family: ${fam}, Arial, sans-serif;`,
        `font-size: ${v.fontSize};`,
        `line-height: ${v.lineHeight};`,
        `font-weight: ${v.fontWeight};`,
        `letter-spacing: ${v.letterSpacing};`,
      ].map(l => indent + l).join('\n');
    };

    // `font` shorthand: weight size/line-height family. Complete by construction.
    const props = (name, v, indent) => {
      const fam = Array.isArray(v.fontFamily) ? v.fontFamily.join(', ') : v.fontFamily;
      return [
        `--sr-type-${name}-font: ${v.fontWeight} ${v.fontSize}/${v.lineHeight} ${fam}, Arial, sans-serif;`,
        `--sr-type-${name}-letter-spacing: ${v.letterSpacing};`,
      ].map(l => indent + l).join('\n');
    };

    const base = [];
    const overrides = [];
    const baseProps = [];
    const overrideProps = [];
    for (const [name, vals] of Object.entries(groups)) {
      const mobile = vals.mobile || vals.desktop;
      const desktop = vals.desktop || vals.mobile;
      base.push(`.sr-type-${name} {\n${decls(mobile, '  ')}\n}`);
      baseProps.push(props(name, mobile, '  '));
      if (JSON.stringify(mobile) !== JSON.stringify(desktop)) {
        overrides.push(`  .sr-type-${name} {\n${decls(desktop, '    ')}\n  }`);
        overrideProps.push(props(name, desktop, '    '));
      }
    }

    let out = `/**\n` +
      ` * Auto-generated by @dhcw/sr-tokens — do not edit manually.\n` +
      ` * Responsive typography utility classes (mobile-first): the base rule is the\n` +
      ` * mobile scale; the desktop scale is applied at min-width: ${desktopMin}.\n` +
      ` * Apply directly, e.g. <h1 class="sr-type-heading-xl">…</h1>\n` +
      ` *\n` +
      ` * Component CSS that cannot add a class uses the composite properties\n` +
      ` * instead — always BOTH, never one:\n` +
      ` *   font: var(--sr-type-body-s-font);\n` +
      ` *   letter-spacing: var(--sr-type-body-s-letter-spacing);\n` +
      // NOTE: never write `*/` inside this emitted comment — including in a
      // token wildcard like `--font-size-*` followed by a slash. It closes the
      // CSS comment early and the remainder swallows the next rule.
      ` * Never hand-pick the raw font-size and line-height tokens to build one.\n` +
      ` */\n\n`;
    out += `:root {\n${baseProps.join('\n')}\n}\n\n`;
    out += base.join('\n\n') + '\n';
    if (overrides.length) {
      out += `\n@media (min-width: ${desktopMin}) {\n  :root {\n${overrideProps.join('\n')}\n  }\n\n${overrides.join('\n\n')}\n}\n`;
    }
    return out;
  }
};

// Composite typography tokens cannot be expressed as single CSS/SCSS variables —
// exclude them from the variable dumps (they are emitted as utility classes instead).
const excludeTypography = (token) => (token.$type || token.type) !== 'typography';

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------
const kebabTransform = {
  name: 'name/kebab-sr',
  type: 'name',
  transform: (token) => {
    return token.path
      .join('-')
      .toLowerCase()
      .replace(/\s+/g, '-');
  }
};

const pascalTransform = {
  name: 'name/pascal-sr',
  type: 'name',
  transform: (token) => {
    return token.path
      .map(p => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
      .replace(/[-\s]+(\w)/g, (_, c) => c.toUpperCase());
  }
};

// ---------------------------------------------------------------------------
// Shared source files (non-colour)
// ---------------------------------------------------------------------------
const sharedSources = [
  `${TOKENS_ROOT}/primitives/spacing.json`,
  `${TOKENS_ROOT}/primitives/typography.json`,
  `${TOKENS_ROOT}/primitives/iconography.json`,
  `${TOKENS_ROOT}/semantic/typography.json`,
  `${TOKENS_ROOT}/semantic/spacing.json`,
  `${TOKENS_ROOT}/breakpoints.json`,
  `${TOKENS_ROOT}/border.json`,
  `${TOKENS_ROOT}/elevation.json`,
  `${TOKENS_ROOT}/touch-targets.json`,
  `${TOKENS_ROOT}/logo-sizing.json`,
];

// Filter out files that don't exist
import { existsSync } from 'fs';
const existingSources = (sources) => sources.filter(s => {
  if (s.includes('*')) return true;
  return existsSync(s);
});

// ---------------------------------------------------------------------------
// Build configs
// ---------------------------------------------------------------------------
function makeConfig(mode) {
  const isDark = mode === 'dark';
  const colorSource = isDark
    ? `${TOKENS_ROOT}/semantic/color.dark.json`
    : `${TOKENS_ROOT}/semantic/color.json`;

  return {
    usesDtcg: true,
    log: { verbosity: 'silent' },
    hooks: {
      preprocessors: {
        'strip-dtcg-meta': (dictionary) => {
          delete dictionary.$schema;
          delete dictionary.$description;
          return dictionary;
        }
      },
      formats: {
        'xaml/resourceDictionary': xamlFormat.format,
        'json/flat-map': flatJsonFormat.format,
        'css/typography-utilities': typographyClassesFormat.format,
      },
      transforms: {
        'name/kebab-sr': kebabTransform,
        'name/pascal-sr': pascalTransform,
      }
    },
    preprocessors: ['strip-dtcg-meta'],
    source: existingSources([
      `${TOKENS_ROOT}/primitives/color.json`,
      colorSource,
      ...sharedSources,
    ]),
    platforms: {
      css: {
        transforms: ['name/kebab-sr', 'color/css'],
        buildPath: 'build/css/',
        prefix: 'sr',
        files: [
          {
            destination: isDark ? 'tokens-dark.css' : 'tokens.css',
            format: 'css/variables',
            filter: excludeTypography,
            options: {
              outputReferences: false,
              selector: isDark ? '[data-theme="dark"]' : ':root'
            }
          },
          // Responsive typography utility classes — light/theme-agnostic, emit once.
          ...(isDark ? [] : [{
            destination: 'typography.css',
            format: 'css/typography-utilities',
          }])
        ]
      },
      scss: {
        transforms: ['name/kebab-sr', 'color/css'],
        buildPath: 'build/scss/',
        prefix: 'sr',
        files: [{
          destination: isDark ? '_tokens-dark.scss' : '_tokens.scss',
          format: 'scss/variables',
          filter: excludeTypography,
          options: { outputReferences: false }
        }]
      },
      ...(isDark ? {} : {
        json: {
          transforms: ['name/kebab-sr', 'color/css'],
          buildPath: 'build/json/',
          files: [{
            destination: 'tokens-flat.json',
            format: 'json/flat-map'
          }]
        }
      }),
      xaml: {
        transforms: ['name/pascal-sr', 'color/css'],
        buildPath: 'build/xaml/',
        files: [{
          destination: isDark ? 'Tokens.Dark.xaml' : 'Tokens.xaml',
          format: 'xaml/resourceDictionary',
          filter: excludeTypography
        }]
      }
    }
  };
}

// ---------------------------------------------------------------------------
// Font face
//
// Roboto is the system's only typeface (DESIGN-SYSTEM.md). It was never
// actually loaded anywhere, so every surface silently fell back — and because
// component CSS disagreed on the fallback stack (`Arial` in the type tokens,
// `system-ui` in a few components), different elements fell back to *different*
// fonts on the same screen. Shipping the face removes the whole class of bug.
//
// Embedded as a data URI rather than a separate file request because the
// prototype embeds run inside a Sandpack iframe where a relative font URL does
// not resolve and a remote one is blocked by CSP. One 43KB variable font covers
// weights 100-900, so this is a single ~58KB base64 blob and no network at all.
//
// Source: Roboto v51 latin subset, Apache License 2.0. See fonts/LICENSE.txt.
// ---------------------------------------------------------------------------
function emitFontFace() {
  const woff2 = readFileSync(path.resolve(__dirname, 'fonts', 'roboto-latin-variable.woff2'));
  const out = `/**
 * Auto-generated by @dhcw/sr-tokens — do not edit manually.
 * Roboto (latin subset, variable 100-900), Apache License 2.0.
 * Embedded as a data URI so the face resolves with no network request and no
 * relative-path assumptions — including inside sandboxed prototype embeds.
 */
@font-face {
  font-family: "Roboto";
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url(data:font/woff2;base64,${woff2.toString('base64')}) format("woff2");
}
`;
  mkdirSync(path.resolve(__dirname, 'build', 'css'), { recursive: true });
  writeFileSync(path.resolve(__dirname, 'build', 'css', 'fonts.css'), out);
  console.log('\nEmitted fonts.css (Roboto embedded,', Math.round(woff2.length / 1024) + 'KB source).');
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
async function build() {
  console.log('\nBuilding light-mode tokens...');
  const sdLight = new StyleDictionary(makeConfig('light'));
  await sdLight.buildAllPlatforms();

  console.log('\nBuilding dark-mode tokens...');
  const sdDark = new StyleDictionary(makeConfig('dark'));
  await sdDark.buildAllPlatforms();

  emitFontFace();

  console.log('\nToken build complete. Outputs in packages/tokens/build/');
}

build().catch(err => {
  console.error('Token build failed:', err);
  process.exit(1);
});
