/**
 * Token build pipeline — Style Dictionary 4.x
 *
 * Reads: /foundations/tokens/ (W3C DTCG format)
 * Outputs:
 *   build/css/tokens.css           — CSS custom properties (light mode)
 *   build/css/tokens-dark.css      — CSS custom properties (dark mode)
 *   build/scss/_tokens.scss        — SCSS variables (light mode)
 *   build/scss/_tokens-dark.scss   — SCSS variables (dark mode)
 *   build/xaml/Tokens.xaml         — XAML ResourceDictionary (light mode, for MAUI)
 *   build/xaml/Tokens.Dark.xaml    — XAML ResourceDictionary (dark mode, for MAUI)
 *   build/json/tokens-flat.json    — Flat key-value JSON (for tooling/CI)
 */

import StyleDictionary from 'style-dictionary';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TOKENS_ROOT = path.resolve(__dirname, '../../foundations/tokens');

// ---------------------------------------------------------------------------
// Custom format: XAML ResourceDictionary for .NET MAUI
// ---------------------------------------------------------------------------
const xamlFormat = {
  name: 'xaml/resourceDictionary',
  format: ({ dictionary }) => {
    const header = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by @dhcw/sr-tokens — do not edit manually -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
`;
    const footer = `</ResourceDictionary>\n`;

    const entries = dictionary.allTokens.map(token => {
      const name = token.name;
      const val = token.$value ?? token.value;
      const type = token.$type || token.type || '';

      if (type === 'color') {
        return `    <Color x:Key="${name}">${val}</Color>`;
      }
      if (type === 'dimension') {
        const numVal = parseFloat(val);
        return `    <x:Double x:Key="${name}">${numVal}</x:Double>`;
      }
      return `    <x:String x:Key="${name}">${val}</x:String>`;
    });

    return header + entries.join('\n') + '\n' + footer;
  }
};

// Flat JSON for tooling
const flatJsonFormat = {
  name: 'json/flat-map',
  format: ({ dictionary }) => {
    const result = {};
    dictionary.allTokens.forEach(token => {
      result[token.name] = token.$value ?? token.value;
    });
    return JSON.stringify(result, null, 2) + '\n';
  }
};

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------
const kebabTransform = {
  name: 'name/kebab-sr',
  type: 'name',
  transform: (token) => {
    return token.path
      .join('-')
      .toLowerCase()
      .replace(/\s+/g, '-');
  }
};

const pascalTransform = {
  name: 'name/pascal-sr',
  type: 'name',
  transform: (token) => {
    return token.path
      .map(p => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
      .replace(/[-\s]+(\w)/g, (_, c) => c.toUpperCase());
  }
};

// ---------------------------------------------------------------------------
// Shared source files (non-colour)
// ---------------------------------------------------------------------------
const sharedSources = [
  `${TOKENS_ROOT}/primitives/spacing.json`,
  `${TOKENS_ROOT}/primitives/typography.json`,
  `${TOKENS_ROOT}/primitives/iconography.json`,
  `${TOKENS_ROOT}/semantic/typography.json`,
  `${TOKENS_ROOT}/semantic/spacing.json`,
  `${TOKENS_ROOT}/breakpoints.json`,
  `${TOKENS_ROOT}/border.json`,
  `${TOKENS_ROOT}/touch-targets.json`,
  `${TOKENS_ROOT}/logo-sizing.json`,
];

// Filter out files that don't exist
import { existsSync } from 'fs';
const existingSources = (sources) => sources.filter(s => {
  if (s.includes('*')) return true;
  return existsSync(s);
});

// ---------------------------------------------------------------------------
// Build configs
// ---------------------------------------------------------------------------
function makeConfig(mode) {
  const isDark = mode === 'dark';
  const colorSource = isDark
    ? `${TOKENS_ROOT}/semantic/color.dark.json`
    : `${TOKENS_ROOT}/semantic/color.json`;

  return {
    usesDtcg: true,
    log: { verbosity: 'silent' },
    hooks: {
      preprocessors: {
        'strip-dtcg-meta': (dictionary) => {
          delete dictionary.$schema;
          delete dictionary.$description;
          return dictionary;
        }
      },
      formats: {
        'xaml/resourceDictionary': xamlFormat.format,
        'json/flat-map': flatJsonFormat.format,
      },
      transforms: {
        'name/kebab-sr': kebabTransform,
        'name/pascal-sr': pascalTransform,
      }
    },
    preprocessors: ['strip-dtcg-meta'],
    source: existingSources([
      `${TOKENS_ROOT}/primitives/color.json`,
      colorSource,
      ...sharedSources,
    ]),
    platforms: {
      css: {
        transforms: ['name/kebab-sr', 'color/css'],
        buildPath: 'build/css/',
        prefix: 'sr',
        files: [{
          destination: isDark ? 'tokens-dark.css' : 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: false,
            selector: isDark ? '[data-theme="dark"]' : ':root'
          }
        }]
      },
      scss: {
        transforms: ['name/kebab-sr', 'color/css'],
        buildPath: 'build/scss/',
        prefix: 'sr',
        files: [{
          destination: isDark ? '_tokens-dark.scss' : '_tokens.scss',
          format: 'scss/variables',
          options: { outputReferences: false }
        }]
      },
      ...(isDark ? {} : {
        json: {
          transforms: ['name/kebab-sr', 'color/css'],
          buildPath: 'build/json/',
          files: [{
            destination: 'tokens-flat.json',
            format: 'json/flat-map'
          }]
        }
      }),
      xaml: {
        transforms: ['name/pascal-sr', 'color/css'],
        buildPath: 'build/xaml/',
        files: [{
          destination: isDark ? 'Tokens.Dark.xaml' : 'Tokens.xaml',
          format: 'xaml/resourceDictionary'
        }]
      }
    }
  };
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
async function build() {
  console.log('\nBuilding light-mode tokens...');
  const sdLight = new StyleDictionary(makeConfig('light'));
  await sdLight.buildAllPlatforms();

  console.log('\nBuilding dark-mode tokens...');
  const sdDark = new StyleDictionary(makeConfig('dark'));
  await sdDark.buildAllPlatforms();

  console.log('\nToken build complete. Outputs in packages/tokens/build/');
}

build().catch(err => {
  console.error('Token build failed:', err);
  process.exit(1);
});
