// AUTO-GENERATED by packages/maui/build-nuget.mjs — do not edit by hand.
namespace DHCW.SingleRecord.Maui;

/// <summary>Colour and elevation tokens, with dark-mode twins.</summary>
public partial class SrColors : ResourceDictionary
{
    public SrColors() => InitializeComponent();
}
