// AUTO-GENERATED by packages/maui/build-nuget.mjs — do not edit by hand.
namespace DHCW.SingleRecord.Maui;

/// <summary>Icon path geometry, one x:String per icon.</summary>
public partial class SrIcons : ResourceDictionary
{
    public SrIcons() => InitializeComponent();
}
