// AUTO-GENERATED by packages/maui/build-nuget.mjs — do not edit by hand.
namespace DHCW.SingleRecord.Maui;

/// <summary>Implicit and keyed control styles, and the type scale. Merge this LAST — it references keys from SrColors and SrIcons.</summary>
public partial class SrStyles : ResourceDictionary
{
    public SrStyles() => InitializeComponent();
}
