// Generates build/icons.js (name -> inner SVG markup map) and build/sprite.svg
// (a single <symbol> sprite) from the canonical source SVGs in
// foundations/iconography/svg/. Run via `npm run build -w @dhcw/sr-icons`.
//
// Source SVGs are the contract (DDR-003 — Lucide, ISC licence, 24x24, 2px
// stroke, currentColor). This script only repackages them for consumption —
// it does not modify icon artwork.

import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const sourceDir = resolve(here, '../../foundations/iconography/svg');
const outDir = resolve(here, 'build');

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (entry.endsWith('.svg')) out.push(full);
  }
  return out;
}

const files = walk(sourceDir).sort();
if (files.length === 0) {
  throw new Error(`No SVG sources found under ${sourceDir}`);
}

const icons = {};
const symbols = [];

for (const file of files) {
  const name = relative(sourceDir, file).replace(/\.svg$/, '').replace(/\\/g, '/');
  const raw = readFileSync(file, 'utf8').trim();

  // Inner markup (paths/etc.) for the icons.js map — strip the outer <svg ...> wrapper.
  const inner = raw.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  icons[name] = inner;

  // Sprite <symbol> — reuse the same viewBox/inner markup, id = icon name with
  // "/" replaced (DOM ids can't contain "/").
  const id = `icon-${name.replace(/\//g, '-')}`;
  symbols.push(`<symbol id="${id}" viewBox="0 0 24 24">${inner}</symbol>`);
}

mkdirSync(outDir, { recursive: true });

const iconsJs = `// AUTO-GENERATED by packages/icons/build.js — do not edit directly.
// Source of truth: foundations/iconography/svg/. Re-run \`npm run build -w @dhcw/sr-icons\`
// after adding/changing source SVGs.

export const icons = ${JSON.stringify(icons, null, 2)};

export const iconNames = Object.keys(icons);

/**
 * Inline SVG markup string for one icon, ready to assign to innerHTML or use
 * directly in a template. Decorative by default (aria-hidden) — pass a label
 * to render it as a meaningful, accessible standalone icon instead.
 */
export function iconMarkup(name, { label } = {}) {
  const inner = icons[name];
  if (inner === undefined) {
    throw new Error(\`Unknown icon "\${name}". See iconNames for the full list.\`);
  }
  const a11y = label
    ? \`role="img" aria-label="\${label}"\`
    : 'aria-hidden="true" focusable="false"';
  return \`<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" \${a11y}>\${inner}</svg>\`;
}
`;

writeFileSync(join(outDir, 'icons.js'), iconsJs);

const spriteSvg = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join('\n')}\n</svg>\n`;
writeFileSync(join(outDir, 'sprite.svg'), spriteSvg);

console.log(`@dhcw/sr-icons: built ${files.length} icons -> build/icons.js, build/sprite.svg`);
